### ISSUE TITLE
help

### ISSUE THREAD

**Issue by riolabz** [benignware/jquery-placepicker#4]
Hello, 

I am  new to GitHub. I am having an issues restricting the placepicker to a particular location say to restrict it to banglore only. Kindly guide me on how it can be done!!

Thanks in advance.

**Comment by rexblack** [comment]
Hi riolabz, 
many thanks for your message.
Please excuse my delayed response. If i got you right, this feature is currently not supported. I'd really like to implement this, but I have to admit, that i'm currently very busy, so it's unlikely that i could do this in the near future. 
Please let me add some further thoughts on this: Aside from the implementation of the plugin, I'm not sure, if it would be even possible to restrict the bounds of Google Maps to a certain location. I think, the most obvious solution could be to validate the location at the server side, refuse the request if necessary and print an error message somewhere at the form to indicate this to the user. This solution does not require an changes at the implementation of the plugin.
Best regards, 
Rafael

**Comment by riolabz** [comment]
Thanks rexblack  for your valuable feedback.

**Comment by pugnascotia** [comment]
You may be able to use the built-in "component restrictions" for this, e.g. the following restrictions completion to the UK (ISO code: GB) only.

```
$('.placepicker').placepicker({
  autoCompleteOptions: { componentRestrictions: { country: 'GB' }}
});
```

This works for me.

See: https://developers.google.com/maps/documentation/javascript/geocoding#ComponentFiltering

**Comment by pugnascotia** [comment]
@rexblack suggest closing this issue.
