### ISSUE TITLE
set map

### ISSUE THREAD

**Issue by akaco** [benignware/jquery-placepicker#5]
Hi 

I tried to set location

var mapPlacepicker = new $(".placepicker").placepicker();

and then  mapPlacepicker.setLocation('37.45','45.40');

but not work , there is any option to set location and reload the map ?
thanks

**Comment by pugnascotia** [comment]
You don't need the "new" keyword in there - try removing that.

**Comment by akaco** [comment]
Hi 
Thanks for your reply  please check the following link then you get what I meaning

https://jsfiddle.net/vfgv7dtz/1/

thanks for your help

**Comment by pugnascotia** [comment]
The '.placepicker()' function returns a jQuery object, not the placepicker object. To get that, you need to do:

```
var mapPlacepicker = $(".placepicker").placepicker().data('placepicker');
```

**Comment by akaco** [comment]
perfect  working like a charm ;)

thanks

**Comment by pugnascotia** [comment]
@rexblack suggest closing this issue.
