### ISSUE TITLE
Could you help me update the version field and add the keywords field in package.json?

### ISSUE THREAD

**Issue by nolsherry** [benignware/jquery-placepicker#7]
Hello @rexblack,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I found the latest version is 0.0.3, but the `version` field in `package.json` is 0.0.2. 
Could you help me update the `version` field in `package.json`, 
By the way, if you have time, please help me add the `keywords` field in `package.json`.
thanks!

cdnjs/cdnjs#9013

**Comment by rexblack** [comment]
Fixed by c661b74 and 3d4a189
Please refer to latest release v0.0.4

Thank you for maintaining cdnjs
